CREATE TABLE USERS (
    USERNAME VARCHAR2(50) PRIMARY KEY,
    PASSWORD_HASH VARCHAR2(4000) NOT NULL,
    SALT VARCHAR2(50),
    HASH_FUNCTION VARCHAR2(50) NOT NULL
);
CREATE TABLE WALLET_ITEMS (
    USERNAME VARCHAR2(50),
    WEB_ADDRESS VARCHAR2(50),
    WEB_ADDRESS_USERNAME VARCHAR2(50) NOT NULL,
    WEB_ADDRESS_PASSWORD VARCHAR2(4000) NOT NULL,
    PRIMARY KEY (USERNAME, WEB_ADDRESS)
);
CREATE TABLE LOG_IN_AUDITS (
    USERNAME VARCHAR2(50) NOT NULL,
    IP_ADDRESS VARCHAR2(100) NOT NULL,
    RESULT VARCHAR2(50),
    CREATION_TIMESTAMP TIMESTAMP NOT NULL,
    PRIMARY KEY (USERNAME, IP_ADDRESS, RESULT, CREATION_TIMESTAMP)
);
CREATE INDEX LOG_IN_AUDIT_IP_ADDRESS_INDEX ON LOG_IN_AUDITS(IP_ADDRESS);
CREATE TABLE BLOCKED_IPS (
    IP_ADDRESS VARCHAR2(100) NOT NULL
);
CREATE TABLE SUBJECT_TO_OBSERVER (
    SUBJECT VARCHAR2(50) NOT NULL,
    OBSERVER VARCHAR2(50) NOT NULL,
    PRIMARY KEY (SUBJECT, OBSERVER)
);
